### PR TITLE
master-qa-27929

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-27929

### CODE REVIEW

**Comment by anthony-chu** [comment]
@koor4356 

please rebase with the following changes:

- make `SiteTemplate#editDescription` configurable by allowing testers to set a `siteTemplateDescription` variable
- rename `EditSiteTemplateNameField` to `EditSiteTemplateName` for consistency between your two tests.

thanks!

**Comment by koor4356** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks!

SF notes for @koor4356:
- merged the tests and macros for changing and viewing site template name and description
- removed some unused macros
- fixed some spelling and variables (wasn't caused by you)

**Comment by anthony-chu** [comment]
Pushed to BChiu.
brianchiu#1503
brianchiu#1504

**Pull request closed without merging**
