### PR TITLE
LRQA-39457 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39457

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Note: there should be 2 unique failures. Wiki does not have option to share to social media for unknown reason, Bug? or Feature not implemented. Other one is a bug of share button not working for message board assets (reported already).

**Comment by kyle-miho** [comment]
https://test-1-7.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2423/jenkins-report.html

**Comment by anthony-chu** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=240575919&testrayRunId=240575933

**Comment by anthony-chu** [comment]
@kyle-miho Can you please rebase your pull and remove the TEMP commit? thanks

**Comment by kyle-miho** [comment]
ci:test

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Some SF notes:
- I extracted the different assertions into separate macros (one for the icons, another for the share menu), and applied those macros throughout
- Since this is for Social Bookmarks, which is a collaboration component, I forwarded the pull to the collab team to take a look at before it goes to BChan.

Pushed to AChiang.
https://github.com/austinchiang/liferay-portal/pull/275

**Pull request closed without merging**
