### PR TITLE
LRQA-39454, LRQA-39455 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39454
https://issues.liferay.com/browse/LRQA-39455

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1454/jenkins-report.html

**Comment by anthony-chu** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=240048936&testrayRunId=240049170

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Some SF notes:
- I updated LRQA-39454 to check for the locator instead of the text, as per our discussion.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56569

**Pull request closed without merging**
