### PR TITLE
LRQA-31873 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-31873

Just sent this to BChan on ee-7.0.x

@anthony-chu Sending this to you, because I wanted to remove the QA-RT label from [EPM-819](https://issues.liferay.com/browse/EPM-819).  Thanks!

### CODE REVIEW

**Comment by anthony-chu** [comment]
Thanks @brianwulbern!

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/48226

**Comment by anthony-chu** [comment]
Sorry, I realized I never closed this. Woops! =D

**Comment by brianwulbern** [comment]
Haha :)

**Pull request closed without merging**
