### PR TITLE
LRQA-40136, LRQA-40137 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-40136
https://issues.liferay.com/browse/LRQA-40137

### CODE REVIEW

**Comment by kyle-miho** [comment]
@anthony-chu Some subtasks not worth the time to fix right now (good amount of work for 1-2 test cases each that are not priority 5) so I am sending in the important fixes.

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Since there typically won't be a need to specifically click the icon based on its current state (i.e., card, list, or table), it is sufficient to click just the icon without specifying the current display style.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/57564

**Pull request closed without merging**
