### PR TITLE
LRQA-42033 Set variable for changing primary navigation menu

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-42033

### CODE REVIEW

**Comment by koor4356** [comment]
ci:relevant

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
@anthony-chu, backport this fixed. Thanks!

**Comment by anthony-chu** [comment]
Thanks @koor4356!

SF notes:
- I updated the variable name from `defaultPrimaryNavigationMenu` to `currentPrimaryNavigationMenu`, since the macro can be used to switch out any primary navigation menu, not just the default one That way, the variable usage is a bit more clear.

**Comment by anthony-chu** [comment]
Pushed to BChan.
master - https://github.com/brianchandotcom/liferay-portal/pull/60976
7.1.x - https://github.com/brianchandotcom/liferay-portal-ee/pull/20806

**Pull request closed without merging**
