### PR TITLE
LRQA-12620 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-12620
https://issues.liferay.com/browse/LRQA-37543

@anthony-chu two test forward-ports.  Thanks!

cc @alee8888 @xbrianlee

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:test

**Comment by brianwulbern** [comment]
@pyoo47 seeing this in the log:
```
[beanshell] Synchronization with local-git failed. Retrying.
[beanshell] java.lang.RuntimeException: Unable to get remote branches from local-git-remote-0 (git@cloud-10-0-0-11:liferay/liferay-subrepo-tools.git)
[beanshell] ssh_exchange_identification: Connection closed by remote host
[beanshell] fatal: Could not read from remote repository.
[beanshell] 
[beanshell] Please make sure you have the correct access rights
[beanshell] and the repository exists.
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getRemoteBranches(GitWorkingDirectory.java:1388)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getBranches(GitWorkingDirectory.java:570)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getBranch(GitWorkingDirectory.java:532)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.branchExists(GitWorkingDirectory.java:135)
```

**Comment by pyoo47** [comment]
@brianwulbern This looks like one of the local-git nodes failed to respond for some reason. We try to minimize these occurrences by excluding nodes that fail to respond to a test git request but sometimes we have bad luck and the node responds to the test request but fails to respond when it really counts. You should be able to retest this with no issues.

**Comment by pyoo47** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks @brianwulbern!

I made a few small SFs
- since `Navigator#getCurrentURL` doesn't take in any parameters, I removed the `var` line from those macro calls
- the content for `maliciousURL` is set once, and the second time it is set with the same content, so I went ahead and removed the second definition of the variable.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54771

**Comment by brianwulbern** [comment]
@pyoo47 good to know, I'll retrigger next time, thanks!

@anthony-chu thanks!

**Pull request closed without merging**
