### PR TITLE
LRQA-36513

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-36513

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:retest

**Comment by jkappler** [comment]
Thanks @anthony-chu!

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
hi @jkappler! it looks like testing is good here. do you want me to go ahead and send a pull to brian for this?

**Comment by jkappler** [comment]
Hi @anthony-chu, that's great news!!!

Lets see what @ealonso thinks about this. If he agrees, then I think it would be great to send it.

Thanks for everything!

**Comment by jkappler** [comment]
Hi @anthony-chu, we have green light! If you want to, you can go ahead and send the PR to Brian 🎉 

Thanks again!

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/54699

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
