### PR TITLE
LRQA-40325 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-40325

### CODE REVIEW

**Comment by kyle-miho** [comment]
Waiting for confirmation of all tests to be deprecated before submitting for review

**Comment by anthony-chu** [comment]
will review after test cases to be removed are confirmed.

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Since the associated paths and macros are also now unused, I've also removed them as well.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/57586

**Pull request closed without merging**
