### PR TITLE
LRQA-39770, LRQA-39962, LRQA-39963 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-39770
https://issues.liferay.com/browse/LRQA-39962
https://issues.liferay.com/browse/LRQA-39963

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test

**Comment by brianwulbern** [comment]
@anthony-chu @liulukiwi is this still needed, or are the affected tests passing at head now?

**Comment by brianwulbern** [comment]
ci:close

**Comment by liulukiwi** [comment]
Pushed to GRen.
GinsonRen#185.

**Pull request closed without merging**
