### PR TITLE
LRQA-32569, LRQA-32634 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-32569
https://issues.liferay.com/browse/LRQA-32634

@anthony-chu please review and forward-port these two training tests, thanks!

### CODE REVIEW

**Comment by anthony-chu** [comment]
hey @brianwulbern, it looks like the LAR file is attached to a particular version of Liferay (in this case, 7010 for DXP) and this prevents a successful upload on master (7003). there are two things we can do at this point:

1. a LAR file specific to master would need to be generated or
1. we end up not front-porting LRQA-32569 since the LAR file is version-bound to DXP.

let me know what you think. thanks!

**Comment by brianwulbern** [comment]
Ah yeah, that is a problem.  Let me ping Jon Omahen in another running email thread to see if they already have some of these LAR files somewhere on master.  And yeah, it seems like they've been bumping their ee-7.0.x LAR files up for each release.

**Comment by brianwulbern** [comment]
@anthony-chu can you hold on to this PR until we hear back?  Thanks

**Comment by anthony-chu** [comment]
@brianwulbern yup, i'll leave this pull open until we hear back.

**Comment by brianwulbern** [comment]
Ok, it's a bug: [LPS-73076](https://issues.liferay.com/browse/LPS-73076).  Jason is requesting that we wait until the bug is fixed before we have the test on master.  Maybe we can add it now and make it ignore="true" adding the QA-RT label to the LPS so we can avert conflicts later on, and simply turn the test on later.  I'll update this pull with an ignore commit.

**Comment by anthony-chu** [comment]
Thanks for looking into it, Brian! I'll wait for the ignore commit on this pull.

**Comment by brianwulbern** [comment]
resent here: https://github.com/anthony-chu/liferay-portal/pull/154

**Pull request closed without merging**
