### PR TITLE
LRQA-38094 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-38094

### CODE REVIEW

**Comment by anthony-chu** [comment]
hey @austinchiang @john-co, thanks for the fix. taking a look at the test results, i'm actually really curious. all the failures seem to be affecting only Sites added from Site Templates (whether pre-populated or manually created during the test). john, do you think you have the bandwidth to investigate this a bit more?

**Comment by john-co** [comment]
@anthony-chu @austinchiang , all of the failures include creating a "Community" site type. When filling in the values for Community site the Save button is outside the view of the web browser. This does not affect regular site creation since the Save button is in view.

**Comment by anthony-chu** [comment]
ah, i see now. thanks makes sense. thanks for the explanation, @john-co!

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54982

**Pull request closed without merging**
