### PR TITLE
LRQA-39592 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39592

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
@kyle-miho i stopped the PR testing, since the issues were not caused by your changes (both of them failed because the firefox binary failed to start up).

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

A small SF note:
- since we want to try to reuse macros where possible, i extracted the clicking of the submit button in the modal into its own macro, and reused it between `Modal#submit` and `Site#viewCannotAddCP`.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56886

**Pull request closed without merging**
