### PR TITLE
LRQA-32568, LRQA-32636, LRQA-32643, LRQA-32644 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-32568
https://issues.liferay.com/browse/LRQA-32636
https://issues.liferay.com/browse/LRQA-32643
https://issues.liferay.com/browse/LRQA-32644

@anthony-chu this is a forward port of https://github.com/brianchandotcom/liferay-portal-ee/pull/17294.

I resolved some conflicts with [LRQA-31103](https://issues.liferay.com/browse/LRQA-31103) not yet getting backported, and allowing for macros that are only on master.  Should be good to go.  Let me know if you spot anything.  Thanks!

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks for the port, @brianwulbern!

I made a few SF changes:
- updated the id of the application portlet decorator from `portlet-decorator` to `portletDecorator`
- `selectApplicationDecorator` needs to be done within an iframe, so I added a call to `IFrame#selectConfigurationFrame` within `selectApplicationDecorator`
- moved the var method definition within the function call to simplify

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/49436

**Comment by brianwulbern** [comment]
Thanks, @anthony-chu!   Yeah...it looks like that LookAndFeel test doesn't work the same between master and ee-7.0.x.

**Pull request closed without merging**
