### PR TITLE
LRQA-34824, LRQA-34846 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-34824
https://issues.liferay.com/browse/LRQA-34846

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@anthony-chu, at least it didn't auto-close this time, please review when you get a chance.  Thanks!

**Comment by brianwulbern** [comment]
fyi @pyoo47 @stsquared99

The above failure output contains the following:

```
[beanshell] Executing commands: git ls-remote -h upstream
[beanshell] Synchronization with local-git failed. Retrying.
[beanshell] java.lang.RuntimeException: Unable to execute bash commands: [git ls-remote -h upstream]
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.executeBashCommands(GitWorkingDirectory.java:1010)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getRemoteBranches(GitWorkingDirectory.java:1090)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getBranches(GitWorkingDirectory.java:453)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getBranch(GitWorkingDirectory.java:426)
[beanshell] 	at com.liferay.jenkins.results.parser.LocalGitSyncUtil.updateLocalUpstreamBranch(LocalGitSyncUtil.java:898)
[beanshell] 	at com.liferay.jenkins.results.parser.LocalGitSyncUtil.synchronizeToLocalGit(LocalGitSyncUtil.java:708)
[beanshell] 	at com.liferay.jenkins.results.parser.LocalGitSyncUtil.synchronizeToLocalGit(LocalGitSyncUtil.java:105)
```

**Comment by anthony-chu** [comment]
ci:retest

**Comment by pyoo47** [comment]
@brianwulbern The failure you referenced was a timeout failure while trying to list the branches in upstream (GitHub). When I look at the [GitHub system status page](https://status.github.com/messages) it shows that they reported a problem at around 8:51 pm (PDT). The failure in the pull request occurred about an hour before then but the description of the problem on GitHub leads me to believe that there's a strong possibility that the issue did not occur all of a sudden but instead probably was gradually getting worse and worse until it became prevalent enough to report publicly as a problem at 8:51 pm. 

**October 11, 2017**

**09:26 PDT** Everything operating normally.
**09:16 PDT** We are monitoring as replication lag recovers. Recently performed actions may be slow to appear.
**08:51 PDT** We're currently experiencing high replication delay on our primary database cluster. Recently performed site actions may not appear in the UI.

**Comment by brianwulbern** [comment]
@pyoo47 that would make sense.  Thanks for investigating!

I'll keep an eye on the status page.

**Comment by anthony-chu** [comment]
Thanks @GinsonRen!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/52223

**Pull request closed without merging**
