### PR TITLE
LRQA-42008 Select iframe

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-42008

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
@anthony-chu backport this to 7.1.x, thanks!

**Comment by anthony-chu** [comment]
Thanks @koor4356!

No test changes necessary.

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/61219
https://github.com/brianchandotcom/liferay-portal-ee/pull/20945

**Pull request closed without merging**
