### PR TITLE
LRQA-31445 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-31445

### CODE REVIEW

**Comment by anthony-chu** [comment]
Thanks @Hanlf @GinsonRen!

I updated the macros in `RoleNavigator` to use our `Navigator#gotoNavItem` command, since they all navigate using paths from `NavBar.path`.

Pushed to BLee.
https://github.com/xbrianlee/liferay-portal/pull/138

**Comment by Hanlf** [comment]
Hi @anthony-chu ,
Thanks for reviewing it.
I don't think this test will pass on master with your two commits:
1. [These two lines](https://github.com/xbrianlee/liferay-portal/pull/138/commits/8868c45387339ed9abe32de93ee1dd088f306b74#diff-8377982885648f080e0cc7c6596d7d32L3) should not be removed, since it needs to go into the `Test UserGroup Role` first.
2. For the macro `gotoAssigneeType`, this `Navigator#gotoNavItem` command doesn't work(Actually the 'NavBar#NAV_ITEM_LINK' doesn't work), since it needs to go the second level navigator bar, not the default navigator bar(like Details, Define Permissions, Assignees), here is the picture about it, it is clearer.
narbar

**Comment by anthony-chu** [comment]
hi @Hanlf! you're right about the changes i made. thanks for checking up on the changes i made. ive closed my pull request to brian. i'll take a look at them again, thanks!

**Comment by anthony-chu** [comment]
thanks for the feedback and correction, @Hanlf. that was my mistake, and thank you for catching it. i've sent a new pull request.

Pushed to BLee.
https://github.com/xbrianlee/liferay-portal/pull/140

**Pull request closed without merging**
