### PR TITLE
master-qa-9558

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-9558

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:retest

**Comment by lesliewong92** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks @koor4356!

Some SF notes:

- Moved the `key_ddlDataDefinitionName` variable definition into the `execute` block in `WebContent#addFeed`
- Extracted the navigation to Web Content Feeds into `WebContentNavigator#gotoFeeds` and used it in `gotoAddFeed` and `gotoEditFeed`
- Reused existing macros in `WebContentNavigator#gotoAddFeed` and `WebContentNavigator#gotoEditFeed`
- Renamed a few variables in `RSS#viewFeedContent` (and its use in the test)

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45715

**Pull request closed without merging**
