### PR TITLE
LRQA-42330 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-42330
Backport to 7.1.x.
@austinchiang

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by anthony-chu** [comment]
Thanks @kyle-miho. I'm going to backport this only to 7.1.x.

**Comment by anthony-chu** [comment]
Pushed to BChan.
master - https://github.com/brianchandotcom/liferay-portal/pull/61333
7.1.x - https://github.com/brianchandotcom/liferay-portal-ee/pull/21003

**Comment by anthony-chu** [comment]
@brianwulbern I sent these only to master + 7.1.x. if you think this will be helpful for you guys on 7.0.x, feel free to cherry-pick them, too.

**Comment by brianwulbern** [comment]
@anthony-chu, I think I'll backport this.  Good find @kyle-miho!

Anthony, can you share the script you use for finding unused locators/macros?

**Pull request closed without merging**
