### PR TITLE
LRQA-39436, LRQA-39449 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39436
https://issues.liferay.com/browse/LRQA-39449

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
There should be unique failures for this test: as they will fail at a point that requires extracting fragment id in Asset Display Pages

**Comment by kyle-miho** [comment]
https://test-1-7.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2422/jenkins-report.html

**Comment by anthony-chu** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=240355190&testrayRunId=240355205

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Some SF notes:
- For LRQA-39436, it's safer to check for an exact match of a fragment instead of simply making sure it's contained within the locator (there can be the case of something like `Fragment 10` vs `Fragment 1`, in which case, searching for `Fragment 1` will return `Fragment 10` first).

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56569

**Pull request closed without merging**
