### PR TITLE
LPS-78736 Reorganize apps

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @anthony-chu,

This is the new organization of control menu:

image

It's possible that we broke some tests, Could you please take a look at it and resend to Brian?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
ci:test

**Comment by anthony-chu** [comment]
also, will the new `SITE_ADMINISTRATION_BUILD` replace the current `SITE_ADMINISTRATION_NAVIGATION` category within site administration?

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by ealonso** [comment]
Hey @anthony-chu,

It is not a real replace, is a new category, that have more portlets

**Comment by anthony-chu** [comment]
hi @ealonso, i took a look at the bundle, and it looks like the Build category is missing from site administration:
image

can you take a look at it when you have a chance? thanks!

**Comment by ealonso** [comment]
Hey @anthony-chu,

I've updated the pull with the fixes.

Thanks for letting me know.

**Comment by anthony-chu** [comment]
ci:retest

**Pull request closed without merging**
