### PR TITLE
LPS-90086 SF

### PR DESCRIPTION
**Pull request by anthony-chu**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test:acceptance

**Comment by anthony-chu** [comment]
ci:test:acceptance

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by vicnate5** [comment]
@anthony-chu Can you confirm the above failures are not related to the MySQL driver change.

This change is high risk.

**Comment by anthony-chu** [comment]
ci:test:environments

**Comment by anthony-chu** [comment]
ci:test:jdk11

**Comment by anthony-chu** [comment]
ci:test:upgrade

**Comment by anthony-chu** [comment]
@vicnate5 there's a failure that consistently happens with these changes:

`PGStaging#ActivateDeactivateRemoteStaging` fails due to a WARN level log message. No functional impact. I haven't been able to reproduce it manually.

**Comment by vicnate5** [comment]
@anthony-chu Yea, doesn't sound like a regression, can we ignore the error?

**Comment by anthony-chu** [comment]
@vicnate5 it's only happening on the environments run, which is a smoke batch. so i don't think we need to do any work in ignoring it there.

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test:jdk11

**Comment by anthony-chu** [comment]
ci:test:environments

**Comment by anthony-chu** [comment]
ci:test:upgrade

**Comment by anthony-chu** [comment]
ci:test

**Pull request closed without merging**
