### PR TITLE
LRQA-29654 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-29654

@anthony-chu I sent this to BChan on 7.0 already here: https://github.com/brianchandotcom/liferay-portal/pull/45502

Consider using this method.  See my comment on https://issues.liferay.com/browse/LRQA-29682

Thanks!

### CODE REVIEW

**Comment by anthony-chu** [comment]
@brianwulbern thanks for sending this my way. it finally makes sense why we have those two for loops in the first place... :sweat_smile:

i'll push this change into bchan for master.

@koor4356

**Comment by anthony-chu** [comment]
Thanks @Hanlf @brianwulbern!

A brief SF note:
- I moved the key_variable use into the execute function block. No functional impact, but since it's the only use of the variable, it was cleaner to move it into the execute.

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45565

**Comment by brianwulbern** [comment]
@anthony-chu ah, that makes sense.  Thanks for moving the key var inside the function call

**Pull request closed without merging**
