### PR TITLE
master-qa-33734

### PR DESCRIPTION
**Pull request by koor4356**

### CODE REVIEW

**Comment by koor4356** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks @koor4356!

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/50362

**Pull request closed without merging**
