### PR TITLE
LPS-76089 Introduce the concept of tabs, for the fix tabs while selecting a page template

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jkappler** [comment]
Hi @anthony-chu, this PR will introduce the new way of selecting the page template to create a page, just as the video that I sent last week. It will probably break a lot of tests. We would be very grateful if you could help us with this.

Thanks a lot

**Comment by jkappler** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
Hi @jkappler @ealonso,

I started taking a brief look at the pull, and it looks great! It looks like some page types are not present here (Link to a Page of This Site, Link to URL, and Page Set). Are we intentionally supporting less page types with this update? Thanks!

**Comment by ealonso** [comment]
Hey @anthony-chu,

Since we created the new concept of navigation with the site navigation menus, those types doesn't make sense when we are creating a new layout, because you have those when you are creating a new site navigation item type, this is the way right now of having those types. 

Also, we decided to not to allow users to change the layout type once you create it.

Please let me know if you have any other question.

Regards,
Eudaldo.

**Comment by anthony-chu** [comment]
@ealonso Thanks for the clarification! We'll go ahead and continue on the fixes!

**Comment by anthony-chu** [comment]
hi @ealonso @jkappler,

We have a test that renames the Welcome page, and upon saving the edits to the Welcome page configuration, a UI error is displayed:

`The first page cannot be of type Portlet.`



In the past, we've been able to save the Welcome page as a portlet page type. Is this going to be changed going forward? Thanks!

**Comment by anthony-chu** [comment]
Thanks @jkappler @ealonso!

Testing here: https://github.com/anthony-chu/liferay-portal/pull/368

**Pull request closed without merging**
