### PR TITLE
LPS-78736 Move Recycle Bin portlet into its own category

### PR DESCRIPTION
**Pull request by anthony-chu**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @anthony-chu,

I've rebased and resend here: https://github.com/anthony-chu/liferay-portal/pull/456

Regards,
Eudaldo

**Pull request closed without merging**
