### PR TITLE
LRQA-42383 Remove add bookmarks via asset publisher from the test

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-42383

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
@anthony-chu backport this to 7.1.x, thanks!

**Comment by anthony-chu** [comment]
Thanks @koor4356!

No test changes necessary.

**Comment by anthony-chu** [comment]
Pushed to BChan.
master - https://github.com/brianchandotcom/liferay-portal/pull/61417
7.1.x - https://github.com/brianchandotcom/liferay-portal-ee/pull/21068

**Pull request closed without merging**
