### PR TITLE
LPS-78736 Extract navigation from macro into testcase

### PR DESCRIPTION
**Pull request by anthony-chu**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test

**Comment by ealonso** [comment]
Hey @anthony-chu,

Do you have any update of this?

Regards,
Eudaldo.

**Comment by anthony-chu** [comment]
hey @ealonso, it looks like ci:test never posted its results here. i'll take a look at the results on testray and see.

**Comment by anthony-chu** [comment]
Hey @ealonso, I just pushed this to Brian.

https://github.com/brianchandotcom/liferay-portal/pull/57737

**Pull request closed without merging**
