### PR TITLE
LRQA-39606 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39606

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:retest

**Comment by kyle-miho** [comment]
ci:retest

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:retest

**Comment by kyle-miho** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:retest:f35a646f88ed7a5a42b7a1e295790a8d4d5c09f3

**Comment by kyle-miho** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56825

**Pull request closed without merging**
