### PR TITLE
LRQA-39423 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39423

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Note: Various fails should occur as a result of DDM fields not yet being localizable.

**Comment by anthony-chu** [comment]
@kyle-miho can you resend this pull please? looks like the `temp` commit is still in here.

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56701

**Pull request closed without merging**
