### PR TITLE
LRQA-31839, LRQA-32640, LRQA-32641, LRQA-33171 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-31839
https://issues.liferay.com/browse/LRQA-32640
https://issues.liferay.com/browse/LRQA-32641
https://issues.liferay.com/browse/LRQA-33171

Here's our forward-port to master.  Thanks, @anthony-chu!

@vicnate5 fyi, we added a new Workflow test in https://github.com/anthony-chu/liferay-portal/pull/157/commits/8eff2e5bfe7579763eed22f3c9641fa6bd22e894.  But I noticed you had previously removed many from that file.  We noticed this test coverage was (at least on the functional level) not covered by a test.  Please veto 32641 if you see fit, thanks!

### CODE REVIEW

**Comment by vicnate5** [comment]
@brianwulbern The new workflow test adds new coverage where we had none. Thanks!

**Comment by anthony-chu** [comment]
Thanks @brianwulbern!

Some SF changes I made:
- for the fields in DocumentsAndMediaEditContract, I moved over to using more generic Select and TextInput fields
- added an option to configure the Status field for a Contract Document
- Refactored `Page#disablePageTemplateInheritChanges` to allow for the toggling of the "Inherit Changes" toggle instead of making the macro a hard disable

Thanks for the front-ports!

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/49768

**Comment by brianwulbern** [comment]
Nice, thanks @anthony-chu!

**Pull request closed without merging**
