### PR TITLE
master-qa-27150

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-27150

@anthony-chu I wanted to have you look over the changes beforehand, since they're rather invasive.  I took out WebContent#addTranslationPGViaWCD and WebContent#addCategoryPGViaWCD, as their functionalities are covered elsewhere.  Thanks!

**Please backport to 7.0.x**

### CODE REVIEW

**Comment by anthony-chu** [comment]
@brianwulbern Can you send a separate pull request for 7.0.x? I believe the category selector differs between master and 7.0.x (master uses the iframe, while 7.0.x uses the modal). thanks!

**Comment by brianwulbern** [comment]
@anthony-chu I would lean towards using the conditional logic, as cherry-picking will become more onerous with the onset of more divergences.  I'll fix it up

**Comment by brianwulbern** [comment]
Ran out of time....tomorrow!

**Comment by brianwulbern** [comment]
ci;retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks!

Just a quick SF note: in `WebcontentpublicationUsecase#AssetPublisherCategoriesLocalization` before we call `AssetPublisherPortlet#configureShowMetadataFieldsPG`, I added a `Navigator#gotoPage` call in order to reset the Asset Publisher view, since clicking on article doesn't allow the portlet topper to display.

**Comment by anthony-chu** [comment]
Pushed to BChiu.
brianchiu#1483
brianchiu#1484

**Pull request closed without merging**
