### PR TITLE
LRQA-39463 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39463

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
There should be one unique failure, related to https://issues.liferay.com/browse/LRQA-39606

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Also, @anthony-chu i realized, maybe my new anchor path could be replaced with a general anchor path since it only checks for a specific id?

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56701

**Pull request closed without merging**
