### PR TITLE
LRQA-42087 Add and set parent page variable

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-42087

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
@anthony-chu, backport this fix. Thanks!

**Comment by anthony-chu** [comment]
Thanks @koor4356!

Some SF notes:
- I simplified and/or combined some of the navigation macros together using `LexiconEntry` macros.

**Comment by anthony-chu** [comment]
Pushed to BChan.
master - https://github.com/brianchandotcom/liferay-portal/pull/61073
7.1.x - https://github.com/brianchandotcom/liferay-portal-ee/pull/20878

**Pull request closed without merging**
