### PR TITLE
LRQA-39608 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39608

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Note: PGAssetpublisher#AddAssetTypesViaAPAndAddRespectivePortletsToSamePage and WorkflowAssetPublisher#ApproveWebContentPG should fail due to seperately filed tickets (LRQA button not working and Liferay window not found)

**Comment by kyle-miho** [comment]
ci:test

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56701

**Pull request closed without merging**
