### PR TITLE
LRQA-38143 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-34397
https://issues.liferay.com/browse/LRQA-38143

@anthony-chu forward port of one test and one addition to a test (https://github.com/anthony-chu/liferay-portal/pull/374/commits/5fbe7c704a556fe8e6bdb094f2a9b5ddf6976565), plus some polish.

@austinchiang note https://github.com/anthony-chu/liferay-portal/pull/374/commits/5fbe7c704a556fe8e6bdb094f2a9b5ddf6976565

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:test

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@anthony-chu those are all flaky missing success messages on different tests.

**Comment by anthony-chu** [comment]
Thanks @brianwulbern! I'll try to take a look at it (either remainder of the week or next week).

**Comment by anthony-chu** [comment]
Thanks @brianwulbern @yunlinsun @GinsonRen!

I made some SF changes
- removed some more `value1` parameters from `AssertElementPresent` and `AssertElementNotPresent` function usages
- nested `key_variables` inside their function usages
- fixed an assertion

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/55856

**Pull request closed without merging**
