### PR TITLE
LRQA-38308 Fix | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-38308

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
https://issues.liferay.com/browse/LRQA-38308

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/55396

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/55403

**Pull request closed without merging**
