### PR TITLE
LRQA-33883, LRQA-33917, LRQA-34121, LRQA-34445, LRQA-34447 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-33883
https://issues.liferay.com/browse/LRQA-33917
https://issues.liferay.com/browse/LRQA-34121
https://issues.liferay.com/browse/LRQA-34445
https://issues.liferay.com/browse/LRQA-34447

@anthony-chu here's the resend of #212. Thanks!

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@anthony-chu rebased this one and running CI from head.

**Comment by brianwulbern** [comment]
@anthony-chu rebased to head. Thanks!

**Comment by anthony-chu** [comment]
Thanks @brianwulbern! Sorry for the delay in reviewing this pull request.

SF notes:
- updated some of the key_variables defined in AlloyEditor.path (see ade70fb)
- consolidated the different `ProductMenu#goto...` macros with a singular `ProductMenu#gotoPortlet` command that takes in `category`, `panel`, and `portlet` parameters (see 7ef25e8)
    - let me know if you think the `ProductMenu#gotoPortlet` macro command would be helpful to have in 7.0.x, and i can see if i can send a modified backport to you into 7.0.x for that.

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/51811

**Comment by brianwulbern** [comment]
@anthony-chu, thanks for the review!  No worries, I know we're all busy :)

That would be a big change to make across _all_ of the current uses of `ProductMenu#gotoSitesContent`.  If you have time and bandwidth, it will be nice to have - but don't feel the need to prioritize it over your other work :)

**Pull request closed without merging**
