### PR TITLE
LPS-80230 Use panel app label if available instead of portlet title

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @anthony-chu,

It's possible that we broke some functional test, we've moved page templates from **control panel > sites > site templates** to **global > build > site pages**. 

Could you please take a look at it and update the test if it is necessary?

Thanks!!
Eudaldo.

cc: @pavel-savinov

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
hi @ealonso. it looks like there's a rebase error that's preventing the pull request tester from running successfully. would you be able to take a look at it? thanks!

**Comment by anthony-chu** [comment]
Thanks @pavel-savinov! I'll take a look at it there.

**Pull request closed without merging**
