### PR TITLE
LPS-77353

### PR DESCRIPTION
**Pull request by marco-leo**
cc @Ithildir @JorgeFerrer @ealonso

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by JorgeFerrer** [comment]
👍

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
hey @marco-leo, there are some issues upstream that are blocking many of our functional tests from running. i'll go ahead and retest once those issues are fixed. thanks!

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:test:sf

**Comment by anthony-chu** [comment]
@marco-leo looks like there were no additional failures caused by these changes. i'll go ahead and forward the pull to brian.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56464

**Pull request closed without merging**
