### PR TITLE
master-qa-27068

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-27068

### CODE REVIEW

**Comment by brianwulbern** [comment]
"This issue LPS-67535 was only fixed on master, but not in ee-7.0.x yet."

@koor4356 @anthony-chu if that's true, then maybe make the commit message start: "LPS-67535..."

**Comment by anthony-chu** [comment]
@brianwulbern That's a good point that you bring up. @koor4356 I'm going to update the commit message to use the LPS ticket so that support can find this test ticket as well when they backport to ee-7.0.x.

**Comment by anthony-chu** [comment]
SF notes for @koor4356:

- Used LPS for commit message so that support can find our test when backporting
- Renamed test per our discussion.

**Comment by anthony-chu** [comment]
Pushed to BChiu.
brianchiu#1476

**Pull request closed without merging**
