### PR TITLE
LRQA-39448 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39448

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1700/jenkins-report.html

**Comment by anthony-chu** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=240366770&testrayRunId=240379915

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56569

**Pull request closed without merging**
