### PR TITLE
LRQA-33829 master

### PR DESCRIPTION
**Pull request by pcwhite**
https://issues.liferay.com/browse/LRQA-33829

### CODE REVIEW

**Comment by pcwhite** [comment]
@austinchiang cc'ed

**Comment by anthony-chu** [comment]
hey @pcwhite, can you please update your commit message to follow the commit messages standards [here](https://github.com/liferay/liferay-qa-ee/blob/liferay-qa-docs/tutorials/training/04-auto-analysis/pages/16-automation-test-commit-standards.markdown)? thanks!

**Comment by pcwhite** [comment]
@anthony-chu @austinchiang Updated commit message!

**Comment by anthony-chu** [comment]
Thanks @pcwhite!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/51624

**Pull request closed without merging**
