### PR TITLE
LRQA-33151, LRQA-33426, LRQA-33628, LRQA-34449 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-33151
https://issues.liferay.com/browse/LRQA-33426
https://issues.liferay.com/browse/LRQA-33628
https://issues.liferay.com/browse/LRQA-34449

Some more forward-ports to master.  Thanks @anthony-chu!

### CODE REVIEW

**Comment by anthony-chu** [comment]
hey @brianwulbern, it looks like there are failures particularly w organizations in this pull. can you take a look into them when you have a chance? thanks!

**Comment by brianwulbern** [comment]
@anthony-chu, yeahh, I'll need to see which locator needs updating on this pull.  Will resend.

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@anthony-chu rebased to head.  Thanks!

**Comment by anthony-chu** [comment]
thanks @brianwulbern. just started reviewing this, but i probably won't be able to finish reviewing this until next week. no need to rebase any more, thanks!

**Comment by brianwulbern** [comment]
Ok, thanks for the heads up @anthony-chu!

**Comment by anthony-chu** [comment]
Thanks @brianwulbern!

I made some SF changes, which you can see here: 0384b80...7864225.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/52223

**Comment by brianwulbern** [comment]
Thanks @anthony-chu!

**Comment by brianwulbern** [comment]
fyi @anthony-chu, I'm backporting your changes to 7.0 (including the three commits from LRQA-35061 (https://github.com/brianchandotcom/liferay-portal/pull/52223/commits/80d100bc558c75ee25f7c7e5c6e1110933533c02), (https://github.com/brianchandotcom/liferay-portal/pull/52223/commits/0670774c1ceff375c8219c177ff9eeeb1136a3d2), (https://github.com/brianchandotcom/liferay-portal/pull/52223/commits/093b08aca03162069af1bb4f2d6235e6598be63b), so you won't need to backport those in the comprehensive backport work you're doing.

**Pull request closed without merging**
