### PR TITLE
LPS-75321 Pause not necessary

### PR DESCRIPTION
**Pull request by ealonso**
Hey @anthony-chu,
Please see my response to your question.

how do users navigate to private pages? 

It should be through the filter in management bar:

pages_-_site_name_-_liferay

I was checking the results for this failing test: CPPagetemplates#AddSitePageTemplate(see https://github.com/ealonso/liferay-portal/pull/1201), so, if you are editing a layout you cannot select a page template, you only can select layout types, if you want to select a page template it should be do when you are adding the page.

Please let me know if you have any other question.

Thanks you very much for your work!! and sorry for the late response, we had the Spanish Symposium and then a took a few days of vacations.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by anthony-chu** [comment]
thanks @ealonso! it looks like when a page is deleted from the Site Pages portlet, some error messages are displayed:


could you please take a look into it when you have the chance? thanks!

**Comment by ealonso** [comment]
Hey @anthony-chu,

I've tried to reproduce the error but I couldn't, Could you please give me more details about it?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
ci:retest

**Pull request closed without merging**
