### PR TITLE
LRQA-38291, LRQA-38049, LRQA-38113 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-38291
https://issues.liferay.com/browse/LRQA-38049
https://issues.liferay.com/browse/LRQA-38113

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:open

**Comment by austinchiang** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
hey @kyle-miho, thanks for the fixes. it looks like the change for `ContentRow#ENTRY_CONTENT_ENTRY_CHECKBOX` is causing other tests to fail. would you be able to look into those failures and resend? thanks!

cc @austinchiang

**Pull request closed without merging**
