### PR TITLE
LPS-76779 Increases version. We are removing a class TranslationManager that wasn't in 7.0 and we don't want in 7.1 but forces us to increase to 3.0.0 anyways

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by anthony-chu** [comment]
Hi @jbalsas! I was looking at the branch, and it looks like when Web Content is configured to use an RTL language (like Hebrew), the title field is not switched from left-to-right to right-to-left. Would you be able to look into this? Here's a screenshot of what it looks like:
after0

**Comment by jbalsas** [comment]
Hey @anthony-chu, sure I will take a look. What about the other one?

**Comment by anthony-chu** [comment]
hey @jbalsas, i was able to fix the other test and get it to work successfully.

**Comment by jbalsas** [comment]
Awesome! Could you send back the PR with that test fixed so I can send it forward if I get the RTL to work?

From the screenshot, it's clear that the language direction is not right, so that might just be a bug on my side. What is the test exactly trying to assert and making it fail? (just to be sure I fix both the behaviour and get the test to run).

Thanks!!

**Comment by anthony-chu** [comment]
sure, i can send the branch with the fixes over to you.

after the set has selected Hebrew to be a web content translation, it asserts that the `ltr` attribute for the web content title field is `rtl`.

**Comment by jbalsas** [comment]
Awesome!! That should be an easy fix!! 🤞 

Thanks for all the help!

**Comment by anthony-chu** [comment]
Updated branch sent here:
https://github.com/jbalsas/liferay-portal/pull/1008

**Comment by anthony-chu** [comment]
I'm sorry, I updated the previous comment. It should be checking the `dir` attribute, not the `ltr` attribute. 😞

**Pull request closed without merging**
