### PR TITLE
LPS-76089 Full Page Application should be instantiable

### PR DESCRIPTION
**Pull request by jkappler**
Hi @anthony-chu, there was another fix applied in the branch that I sent you last time. This time I applied it in a different commit, so everything should work.

Thanks again for everything.

cc:// @ealonso

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Pull request closed without merging**
