### PR TITLE
LRQA-34969 Create gotoSitesCommerce macro in ProductMenu.macro

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-34969

 @anthony-chu consolidating this macro from the commerce module into central to match the others, see ticket. Relevant test changes will go through the commerce sub-repo. No rush on this pull. Thanks

### CODE REVIEW

**Comment by jpince** [comment]
eventually, we should consider moving [all of the goto* macro commands](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/macros/ProductMenu.macro#L186-L233) into one, but that can be for another day :)

**Comment by anthony-chu** [comment]
@jpince Thanks, i'll take a look at this. and the goto* consolidation is something that's been on my mind for a bit.

**Comment by anthony-chu** [comment]
also, should this only go to master, or do we want to include this code in 7.0.x as well? if we want it in 7.0.x, i can cherry-pick this and send it to ginson as well.

**Comment by jpince** [comment]
@anthony-chu please DO NOT backport, Commerce is only compatible with 7.1+.

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
thanks @jpince, only sending to master.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/51566

**Pull request closed without merging**
