### PR TITLE
LRQA-33015, LRQA-33110, LRQA-33173, LRQA-33315, LRQA-33368, LRQA-33379 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-33015
https://issues.liferay.com/browse/LRQA-33110
https://issues.liferay.com/browse/LRQA-33173
https://issues.liferay.com/browse/LRQA-33315
https://issues.liferay.com/browse/LRQA-33368
https://issues.liferay.com/browse/LRQA-33379

@anthony-chu Forward-port of some more tests - I can rebase next week if needed, but just wanted to get the port ready (maybe let's wait until https://github.com/brianchandotcom/liferay-portal/pull/50156 goes in, then we'll try https://github.com/anthony-chu/liferay-portal/pull/162, then deal with these tests).  Thanks!

### CODE REVIEW

**Comment by anthony-chu** [comment]
@vicnate5 @sharonchoi @austinchiang @patriciajeanperez @alee8888can you guys take a look at these changes? they affect

**Comment by vicnate5** [comment]
https://github.com/anthony-chu/liferay-portal/pull/164/commits/cf6427da9539a9ce4da5ce9f889152aa6f8b76e6 includes a .bat file. Is that intended?

**Comment by anthony-chu** [comment]
I don't think the `gb.bat` is intentional. i'm planning to remove it.

**Comment by vicnate5** [comment]
https://github.com/anthony-chu/liferay-portal/pull/164/commits/ae54ed557ed7e0b8c77135386732a5d472e0ee27 does not increment the i variable, so this will run 15 times instead of 5

**Comment by brianwulbern** [comment]
Looks like I accidentally made that one a performance test, nice catch @vicnate5

**Comment by brianwulbern** [comment]
And yeah, `gb.bat` inclusion was unintentional, thanks for spotting that @anthony-chu @vicnate5!

**Comment by brianwulbern** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/50156 is now in, I'll rebase https://github.com/anthony-chu/liferay-portal/pull/162

**Comment by patriciajeanperez** [comment]
LRQA-33315 looks good. Thanks, @brianwulbern @anthony-chu

**Comment by brianwulbern** [comment]
@anthony-chu rebased to head. Thanks!

**Comment by anthony-chu** [comment]
Thanks @brianwulbern!

Some SF changes that were made:
- I updated the loop in `CalendarCreateEvent#AddEventWithLargeDateRange` to iterate the `refreshCount` variable to make sure it only refreshes 5 times.
- Removed the gb.bat file that was accidentally committed (amended before pushing)
- Added priority to `UIInfrastrutureUsecase#ViewNonACSIICharactersWithSPADisabled` (based on Raven's initial FP)
- Added the ignore tag to `MessageboardsUsecase#ImportLAR` since it's affected by [LPS-73076](https://issues.liferay.com/browse/LPS-73076).
- Moved `SitesadministrationUsecase#SiteTemplateXSS` to `CPSitetemplates#SiteTemplateXSS`, since it's testing specifically the Site Template. Also simplified disabling the propagation of changes to the site template by doing it when the site is added
- Simplified `SitesUsecase#AddChildSiteFromImportedSiteTemplate` by reusing existing macros; also added the test to the pending list of acceptance tests since this belongs to training.

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/50233

**Comment by brianwulbern** [comment]
Thanks @anthony-chu!

**Comment by brianwulbern** [comment]
I think for 180586183aed81f9380d6dabaf83c367999f8f3d the steps want to Edit the site and check the alert doesn't display, but it _should_ display on site creation if there's a bug there.  Step 4 on [LRQA-33015](https://issues.liferay.com/browse/LRQA-33015) isn't clear if the Site creation is completed then, or just starting then.  I might use your simplification on ee-7.0.x, and just add an extra Save button click + AssertAlertNotPresent.

**Pull request closed without merging**
