### PR TITLE
LRQA-39768 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39768

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
Thanks @kyle-miho!

Some SF changes:
- I refactored how `portletName` and `key_portletName` were being set so that we only have to validate once (just one `if` rather than an `if/else`.
- Let's make sure we call variables explicitly; it serves several purposes:
    1. (this is a technical reason) - Poshi macros and functions prefer explicit variable declaration as opposed to implicit variable declaration
    1. (this is a clarity reason) - Explicitly declaring where our variables are used helps communicate to others looking at our tests what variables need to be there, what variables they need to define, and where they are being used.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56789

**Pull request closed without merging**
