### PR TITLE
LRQA-39445 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-39445

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:reopen

**Comment by kyle-miho** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/57570

**Pull request closed without merging**
