### PR TITLE
master-qa-28817

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-28817

### CODE REVIEW

**Comment by anthony-chu** [comment]
another comment

**Comment by koor4356** [comment]
Add this test to ee-7.0.x, thanks!

**Comment by anthony-chu** [comment]
Thanks @koor4356!

Some SF notes:
- moved the macro to add translations to PortletEntry, since it can be reused across portal
- added and used a macro to click the add icon and select a menu item entry to add
- combined `Button#clickSave` and `Alert#viewSuccessMessage` into `PortletEntry#save` macro call
- since the first time we add a site name is using the English language, we don't need to localize
- updated Spanish translation for Site Name
- the `Click` function used in `Page#viewSiteNameTranslation` doesn't take a value1 parameter, so i went ahead and removed it
- the teardown needs the site to be returned to English, so I added a `Language#tearDownLanguagePG` call at the end of the test.

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/46767
https://github.com/brianchandotcom/liferay-portal/pull/46768

**Pull request closed without merging**
