### PR TITLE
LRQA-33844 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-33844

@anthony-chu, I already sent ee-7.0.x to BChan here: https://github.com/brianchandotcom/liferay-portal-ee/pull/17863.  Thanks!

@christianstokes you can send me pulls on ee-* branches, but I tend to send master pulls back to US portal team before they go to BChan.  This way, your master pulls will get merged faster, since you won't have to send them through me.  So you can send the pulls along those routes, thanks!

/cc @frankfu926

### CODE REVIEW

**Comment by anthony-chu** [comment]
thanks @brianwulbern! i took a look at the ee-7.0.x PR, and it doesn't look like the fix for LRQA-33844 is on there. do you want me to send it in to master first?

**Comment by brianwulbern** [comment]
Ah, yeah @anthony-chu, it was mislabeled and I forgot to give the right commit message.  Should be https://issues.liferay.com/browse/LRQA-33822

**Comment by brianwulbern** [comment]
Pushed ee-7.0.x to BChan (for reals this time).
https://github.com/brianchandotcom/liferay-portal-ee/pull/17885

/cc @anthony-chu @frankfu926 @christianstokes

**Comment by anthony-chu** [comment]
Thanks @frankfu926 @brianwulbern!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/50601

cc @christianstokes

**Pull request closed without merging**
