### PR TITLE
LPS-77353

### PR DESCRIPTION
**Pull request by marco-leo**
@JorgeFerrer  @anthony-chu This is the pull for the starter kit

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by anthony-chu** [comment]
hi @marco-leo @ealonso @jorgeferrer,

it looks like when a site is created, it is by default in the Inactive state. is this behavior intended?

**Comment by marco-leo** [comment]
@JorgeFerrer @anthony-chu  @ealonsoI already sent the fix for this.

**Comment by anthony-chu** [comment]
Thanks @marco-leo!

Testing here: https://github.com/anthony-chu/liferay-portal/pull/397

**Pull request closed without merging**
