### PR TITLE
master-qa-33043

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-33043

### CODE REVIEW

**Comment by anthony-chu** [comment]
hey @koor4356, i like the solution you have proposed here, particularly with checking and validating the states after the sort order is toggled. however, it looks like we are passively toggling the sort direction and not actively sorting them. do you think it's possible to update 6b876d8 to add a check for a variable as well? i think that would help us know, when we call the macro, which way we want the Asset Publisher portlet to sort the articles. let me know if you have questions about this. thanks!

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks for making the changes, @koor4356!

There was an SF change I made:
- instead of using two different locators to check the state, we can use just one locator. also, since the specific locator changes based on what we want / what we click, I updated the locator we click to be more generic so that we can click it regardless of state.

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/49737

**Pull request closed without merging**
