### PR TITLE
master-qa-31007

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-31007

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop (bug in ci script)

**Comment by pyoo47** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
Thanks @koor4356!

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/47249

**Pull request closed without merging**
