### PR TITLE
LRQA-32244, LRQA-33172, LRQA-33348, LRQA-33645, LRQA-33884, LRQA-33942, LRQA-34446, LRQA-34728 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-32244
https://issues.liferay.com/browse/LRQA-33172
https://issues.liferay.com/browse/LRQA-33348
https://issues.liferay.com/browse/LRQA-33645
https://issues.liferay.com/browse/LRQA-33884
https://issues.liferay.com/browse/LRQA-33942
https://issues.liferay.com/browse/LRQA-34446
https://issues.liferay.com/browse/LRQA-34728

@anthony-chu, more forward-ports from 7.0 coverage.  I rebased and resolved conflicts along the way.  Let me know if you have questions about any of them.  Thanks!

p.s. lol, sorry for the big dump of commits...

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
thanks @brianwulbern! if i have changes to recommend, should i make them and send a pr to 7.0.x as well, or should i just go ahead and merge now and then note the changes to make?

**Comment by brianwulbern** [comment]
Mm, if you have time, you can send a pull on 7.0.x.  But I'm ok doing that too :)

**Comment by brianwulbern** [comment]
@anthony-chu rebased it for you.  I've got another one on the way, sorry :/

**Comment by anthony-chu** [comment]
Thanks @brianwulbern!

I combined some of function/macro calls into single macro calls.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/51622

**Pull request closed without merging**
