### PR TITLE
LPS-76089

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-76089

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
@jkappler @ealonso it looks like there are some integration test failures with Layouts. would you guys be able to look into them? thanks!

**Comment by jkappler** [comment]
Hi @anthony-chu. Will take a look first thing in the morning.

Thanks for everything

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
