### PR TITLE
LPS-77353 Update site type selection

### PR DESCRIPTION
**Pull request by anthony-chu**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
thanks @Ithildir!

@marco-leo it looks like the "Members" category in the product menu does not display when a new site is created. it should display between the "Content" and "Configuration" categories. would you be able to look into it? thanks!

image

**Comment by marco-leo** [comment]
@anthony-chu sent a new pull to https://github.com/anthony-chu/liferay-portal/pull/408  in my local I was not able to reproduce it. I just saw an error in the log about a package version to increament.

**Comment by anthony-chu** [comment]
Resent to #408.

**Pull request closed without merging**
