### PR TITLE
LPS-76089

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-38445

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by anthony-chu** [comment]
ci:close

**Comment by anthony-chu** [comment]
resent here: #367

**Pull request closed without merging**
