### PR TITLE
LPS-77353

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@anthony-chu I will force a retest, I am not able to reproduce this in my local, and the changes in the pull are not related  ci:retest

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@ealonso @jorgeferrer can you help me in this pull?

**Comment by JorgeFerrer** [comment]
@anthony-chu there seem to be a few test failures that are indeed related to the pull. It's probably because they create a site during the test. 

Could you review them and have them fixed?

Thanks!

**Comment by anthony-chu** [comment]
hey @marco-leo, i found out what was wrong - it looks like when a site is created, the setting "Allow Manual Membership Management" is disabled, and this has been enabled by default in the past.

**Comment by marco-leo** [comment]
@anthony-chu just sent the fix for this.

**Comment by marco-leo** [comment]
ci:test

**Comment by anthony-chu** [comment]
Thanks @marco-leo! I tested it locally, and it works! I think one issue I anticipate coming up (which we've encountered with the new site pages creation process) is that if a user were to define a required vocabulary for sites, the site would not be created. you can see what the issue may look like here:
https://issues.liferay.com/browse/LPS-78753

cc @jkappler

**Comment by anthony-chu** [comment]
Also a `PortletException` is thrown when trying to add a child site:

1. Navigate to Control Panel > Sites > Sites
1. Click [ + ] and select "Blank Site"
1. Provide a site name and submit
1. Return to list of sites
1. Click kebab for added site and select "Add Child Site"

**Expected result:** User is able to add a child site
**Actual result:** `PortletException` is thrown
```
2018-03-19 16:17:54.299 ERROR [http-nio-8080-exec-2][PortletServlet:112] javax.portlet.PortletException: Path /view_layout_set_prototypes.jsp is not accessible by this portletjavax.portlet.PortletException: Path /view_layout_set_prototypes.jsp is not accessible by this portlet
        at com.liferay.portal.kernel.portlet.LiferayPortlet.checkPath(LiferayPortlet.java:263)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:592)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:610)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:494)
        at com.liferay.site.admin.web.internal.portlet.SiteAdminPortlet.doDispatch(SiteAdminPortlet.java:410)
        at javax.portlet.GenericPortlet.render(GenericPortlet.java:262)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:317)
        at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:103)
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:57)
        at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:100)
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:64)
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:108)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:118)
        at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
        at com.liferay.portlet.InvokerPortletImpl.invoke(InvokerPortletImpl.java:535)
        at com.liferay.portlet.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:610)
        at com.liferay.portlet.InvokerPortletImpl.render(InvokerPortletImpl.java:394)
        at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.render(MonitoringInvokerPortlet.java:265)
        at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1586)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64)
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:78)
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
        at com.liferay.portal.servlet.TransferHeadersHelperImpl$TransferHeadersRequestDispatcher.include(TransferHeadersHelperImpl.java:162)
        at com.liferay.portlet.PortletContainerImpl._render(PortletContainerImpl.java:716)
        at com.liferay.portlet.PortletContainerImpl.render(PortletContainerImpl.java:174)
        at com.liferay.portlet.SecurityPortletContainerWrapper.render(SecurityPortletContainerWrapper.java:141)
        at com.liferay.portlet.RestrictPortletContainerWrapper.render(RestrictPortletContainerWrapper.java:141)
        at com.liferay.portal.kernel.portlet.PortletContainerUtil.render(PortletContainerUtil.java:172)
        at com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor.processMax(TemplateProcessor.java:178)
        at sun.reflect.GeneratedMethodAccessor803.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:389)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:378)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:270)
```

**Comment by marco-leo** [comment]
@anthony-chu I solved the "Child Site" creation. Thanks

**Comment by marco-leo** [comment]
@anthony-chu About the bug you are reporting  https://issues.liferay.com/browse/LPS-78753,

I wil suggest to wait  @jkappler @ealonso solution for the page creation, and than apply the same solution to the site creation. 

Please tell me if is possible to send this pull to Brian.

Thanks

//cc @JorgeFerrer

**Comment by JorgeFerrer** [comment]
@beatrizma is going to look into this for both, page creation and site creation

**Comment by anthony-chu** [comment]
Thanks @marco-leo!

@JorgeFerrer do we want to wait for the resolution of the page/site creation process to merge this, or shall we merge this in while we wait for the resolution of the page/site creation process?

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/56409

**Pull request closed without merging**
